FROM python
WORKDIR /server
ADD . /server

RUN pip install --upgrade pip


RUN pip install Flask
RUN pip install flask_restful
RUN pip install JWT
RUN pip install flask_jwt
RUN pip install PyJWT==1.7.1
RUN pip install Werkzeug
RUN pip install peewee



#RUN pip install --no-cache -r requirements.txt



EXPOSE 80
